VPATH=.:..
CC=gcc
CFLAGS= -O2 -I../F2CLIBS
AR=ar
ARFLAGS=cr
SHELL=/bin/csh
all: \
	dbdsqr.o \
	dcopy.o \
	dgebd2.o \
	dgebrd.o \
	dgelq2.o \
	dgelqf.o \
	dgemm.o \
	dgemv.o \
	dgeqr2.o \
	dgeqrf.o \
	dger.o \
	dgesvd.o \
	dlabrd.o \
	dlacpy.o \
	dlamch.o \
	dlange.o \
	dlapy2.o \
	dlarf.o \
	dlarfb.o \
	dlarfg.o \
	dlarft.o \
	dlartg.o \
	dlas2.o \
	dlascl.o \
	dlaset.o \
	dlasq1.o \
	dlasq2.o \
	dlasq3.o \
	dlasq4.o \
	dlasr.o \
	dlasrt.o \
	dlassq.o \
	dlasv2.o \
	dnrm2.o \
	dorg2r.o \
	dorgbr.o \
	dorgl2.o \
	dorglq.o \
	dorgqr.o \
	dorm2r.o \
	dormbr.o \
	dorml2.o \
	dormlq.o \
	dormqr.o \
	drot.o \
	dscal.o \
	dswap.o \
	dtrmm.o \
	dtrmv.o \
	ilaenv.o \
	lsame.o \
	xerbla.o \
	libclasvd.a

#
# Library functions:
#
dbdsqr.o:dbdsqr.c
	$(CC) -c -o dbdsqr.o $(CFLAGS) dbdsqr.c
dcopy.o:dcopy.c
	$(CC) -c -o dcopy.o $(CFLAGS) dcopy.c
dgebd2.o:dgebd2.c
	$(CC) -c -o dgebd2.o $(CFLAGS) dgebd2.c
dgebrd.o:dgebrd.c
	$(CC) -c -o dgebrd.o $(CFLAGS) dgebrd.c
dgelq2.o:dgelq2.c
	$(CC) -c -o dgelq2.o $(CFLAGS) dgelq2.c
dgelqf.o:dgelqf.c
	$(CC) -c -o dgelqf.o $(CFLAGS) dgelqf.c
dgemm.o:dgemm.c
	$(CC) -c -o dgemm.o $(CFLAGS) dgemm.c
dgemv.o:dgemv.c
	$(CC) -c -o dgemv.o $(CFLAGS) dgemv.c
dgeqr2.o:dgeqr2.c
	$(CC) -c -o dgeqr2.o $(CFLAGS) dgeqr2.c
dgeqrf.o:dgeqrf.c
	$(CC) -c -o dgeqrf.o $(CFLAGS) dgeqrf.c
dger.o:dger.c
	$(CC) -c -o dger.o $(CFLAGS) dger.c
dgesvd.o:dgesvd.c
	$(CC) -c -o dgesvd.o $(CFLAGS) dgesvd.c
dlabrd.o:dlabrd.c
	$(CC) -c -o dlabrd.o $(CFLAGS) dlabrd.c
dlacpy.o:dlacpy.c
	$(CC) -c -o dlacpy.o $(CFLAGS) dlacpy.c
dlamch.o:dlamch.c
	$(CC) -c -o dlamch.o $(CFLAGS) dlamch.c
dlange.o:dlange.c
	$(CC) -c -o dlange.o $(CFLAGS) dlange.c
dlapy2.o:dlapy2.c
	$(CC) -c -o dlapy2.o $(CFLAGS) dlapy2.c
dlarf.o:dlarf.c
	$(CC) -c -o dlarf.o $(CFLAGS) dlarf.c
dlarfb.o:dlarfb.c
	$(CC) -c -o dlarfb.o $(CFLAGS) dlarfb.c
dlarfg.o:dlarfg.c
	$(CC) -c -o dlarfg.o $(CFLAGS) dlarfg.c
dlarft.o:dlarft.c
	$(CC) -c -o dlarft.o $(CFLAGS) dlarft.c
dlartg.o:dlartg.c
	$(CC) -c -o dlartg.o $(CFLAGS) dlartg.c
dlas2.o:dlas2.c
	$(CC) -c -o dlas2.o $(CFLAGS) dlas2.c
dlascl.o:dlascl.c
	$(CC) -c -o dlascl.o $(CFLAGS) dlascl.c
dlaset.o:dlaset.c
	$(CC) -c -o dlaset.o $(CFLAGS) dlaset.c
dlasq1.o:dlasq1.c
	$(CC) -c -o dlasq1.o $(CFLAGS) dlasq1.c
dlasq2.o:dlasq2.c
	$(CC) -c -o dlasq2.o $(CFLAGS) dlasq2.c
dlasq3.o:dlasq3.c
	$(CC) -c -o dlasq3.o $(CFLAGS) dlasq3.c
dlasq4.o:dlasq4.c
	$(CC) -c -o dlasq4.o $(CFLAGS) dlasq4.c
dlasr.o:dlasr.c
	$(CC) -c -o dlasr.o $(CFLAGS) dlasr.c
dlasrt.o:dlasrt.c
	$(CC) -c -o dlasrt.o $(CFLAGS) dlasrt.c
dlassq.o:dlassq.c
	$(CC) -c -o dlassq.o $(CFLAGS) dlassq.c
dlasv2.o:dlasv2.c
	$(CC) -c -o dlasv2.o $(CFLAGS) dlasv2.c
dnrm2.o:dnrm2.c
	$(CC) -c -o dnrm2.o $(CFLAGS) dnrm2.c
dorg2r.o:dorg2r.c
	$(CC) -c -o dorg2r.o $(CFLAGS) dorg2r.c
dorgbr.o:dorgbr.c
	$(CC) -c -o dorgbr.o $(CFLAGS) dorgbr.c
dorgl2.o:dorgl2.c
	$(CC) -c -o dorgl2.o $(CFLAGS) dorgl2.c
dorglq.o:dorglq.c
	$(CC) -c -o dorglq.o $(CFLAGS) dorglq.c
dorgqr.o:dorgqr.c
	$(CC) -c -o dorgqr.o $(CFLAGS) dorgqr.c
dorm2r.o:dorm2r.c
	$(CC) -c -o dorm2r.o $(CFLAGS) dorm2r.c
dormbr.o:dormbr.c
	$(CC) -c -o dormbr.o $(CFLAGS) dormbr.c
dorml2.o:dorml2.c
	$(CC) -c -o dorml2.o $(CFLAGS) dorml2.c
dormlq.o:dormlq.c
	$(CC) -c -o dormlq.o $(CFLAGS) dormlq.c
dormqr.o:dormqr.c
	$(CC) -c -o dormqr.o $(CFLAGS) dormqr.c
drot.o:drot.c
	$(CC) -c -o drot.o $(CFLAGS) drot.c
dscal.o:dscal.c
	$(CC) -c -o dscal.o $(CFLAGS) dscal.c
dswap.o:dswap.c
	$(CC) -c -o dswap.o $(CFLAGS) dswap.c
dtrmm.o:dtrmm.c
	$(CC) -c -o dtrmm.o $(CFLAGS) dtrmm.c
dtrmv.o:dtrmv.c
	$(CC) -c -o dtrmv.o $(CFLAGS) dtrmv.c
ilaenv.o:ilaenv.c
	$(CC) -c -o ilaenv.o $(CFLAGS) ilaenv.c
lsame.o:lsame.c
	$(CC) -c -o lsame.o $(CFLAGS) lsame.c
xerbla.o:xerbla.c
	$(CC) -c -o xerbla.o $(CFLAGS) xerbla.c
#
# Libraries:
#
libclasvd.a: \
	dbdsqr.o \
	dcopy.o \
	dgebd2.o \
	dgebrd.o \
	dgelq2.o \
	dgelqf.o \
	dgemm.o \
	dgemv.o \
	dgeqr2.o \
	dgeqrf.o \
	dger.o \
	dgesvd.o \
	dlabrd.o \
	dlacpy.o \
	dlamch.o \
	dlange.o \
	dlapy2.o \
	dlarf.o \
	dlarfb.o \
	dlarfg.o \
	dlarft.o \
	dlartg.o \
	dlas2.o \
	dlascl.o \
	dlaset.o \
	dlasq1.o \
	dlasq2.o \
	dlasq3.o \
	dlasq4.o \
	dlasr.o \
	dlasrt.o \
	dlassq.o \
	dlasv2.o \
	dnrm2.o \
	dorg2r.o \
	dorgbr.o \
	dorgl2.o \
	dorglq.o \
	dorgqr.o \
	dorm2r.o \
	dormbr.o \
	dorml2.o \
	dormlq.o \
	dormqr.o \
	drot.o \
	dscal.o \
	dswap.o \
	dtrmm.o \
	dtrmv.o \
	ilaenv.o \
	lsame.o \
	xerbla.o \
	;$(AR) $(ARFLAGS) ../libclasvd.a dbdsqr.o dcopy.o dgebd2.o dgebrd.o dgelq2.o dgelqf.o dgemm.o dgemv.o dgeqr2.o dgeqrf.o dger.o dgesvd.o dlabrd.o dlacpy.o dlamch.o dlange.o dlapy2.o dlarf.o dlarfb.o dlarfg.o dlarft.o dlartg.o dlas2.o dlascl.o dlaset.o dlasq1.o dlasq2.o dlasq3.o dlasq4.o dlasr.o dlasrt.o dlassq.o dlasv2.o dnrm2.o dorg2r.o dorgbr.o dorgl2.o dorglq.o dorgqr.o dorm2r.o dormbr.o dorml2.o dormlq.o dormqr.o drot.o dscal.o dswap.o dtrmm.o dtrmv.o ilaenv.o lsame.o xerbla.o 
